FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install

# This could be left out, because we use reference to the original folder on our PC
COPY --chown=node:node ./ ./

CMD ["npm", "start"]